  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
    generation: 1
    name: demotest-ingress
    namespace: demotest-ns
  spec:
    rules:
    - host: demotest.local
      http:
        paths:
        - backend:
            service:
              name: demotest
              port:
                number: 80
          path: /
          pathType: Prefix
