apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
  generation: 1
  name: {{ .Chart.Name }}-ingress
  namespace: {{ .Chart.Name }}-ns
spec:
  rules:
  - host: {{ .Chart.Name }}.local
    http:
      paths:
      - backend:
          service:
            name: {{ .Chart.Name }}-svc
            port:
              number: 80
        path: /
        pathType: Prefix
