apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
    generation: 1
    name: demoapp-ingress
    namespace: demoapp-ns
  spec:
    rules:
    - host: demoapp.local
      http:
        paths:
        - backend:
            service:
              name: demoapp-svc
              port:
                number: 80
          path: /
          pathType: Prefix
